{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.0.39.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.0.39.aar",
          "size": 4765,
          "sha512": "d60833e9733c92d2875353a6c01596a3bf1c3fa8f5b5215c90c7dc134f559124317b5593515f74a3a3db258b87cb8d83b408cd5ec19f16d0c3051e776ee361b1",
          "sha256": "0987d12283c2c90d4f0b73f0f1daf1e14ac6ddcd407303af7a5e039061c63de7",
          "sha1": "9849782e773a381660914634d3f68f7bb4628db2",
          "md5": "6e980e20678bef947d64fef92999c7c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.0.39.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.0.39.aar",
          "size": 4765,
          "sha512": "d60833e9733c92d2875353a6c01596a3bf1c3fa8f5b5215c90c7dc134f559124317b5593515f74a3a3db258b87cb8d83b408cd5ec19f16d0c3051e776ee361b1",
          "sha256": "0987d12283c2c90d4f0b73f0f1daf1e14ac6ddcd407303af7a5e039061c63de7",
          "sha1": "9849782e773a381660914634d3f68f7bb4628db2",
          "md5": "6e980e20678bef947d64fef92999c7c1"
        }
      ]
    }
  ]
}
