{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_module",
    "module": "flutter_release",
    "version": "0.0.0+12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.0+12.aar",
          "url": "flutter_release-0.0.0+12.aar",
          "size": 4721663,
          "sha512": "57b612268761b8f069fe5936bec713eca6044d3a8ffc82287d328e8545697379432da3e95039d5286f67a88980f202e2fe8548fab9e47dd6abed443dda9e9696",
          "sha256": "d71192add17f4b6665608edb70a08ac164da3351469d6ce956fbf08b81d12233",
          "sha1": "2a03eb4d57ad115f2a383956326a41877d94b8cf",
          "md5": "b8a368dd53f645bb4500de69c8093d59"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.0+12.aar",
          "url": "flutter_release-0.0.0+12.aar",
          "size": 4721663,
          "sha512": "57b612268761b8f069fe5936bec713eca6044d3a8ffc82287d328e8545697379432da3e95039d5286f67a88980f202e2fe8548fab9e47dd6abed443dda9e9696",
          "sha256": "d71192add17f4b6665608edb70a08ac164da3351469d6ce956fbf08b81d12233",
          "sha1": "2a03eb4d57ad115f2a383956326a41877d94b8cf",
          "md5": "b8a368dd53f645bb4500de69c8093d59"
        }
      ]
    }
  ]
}
