{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.38.aar",
          "url": "shared_preferences_android_release-0.0.38.aar",
          "size": 12837,
          "sha512": "eccbf136f59649f873f621d8fbb31090958341469213b74ac0303c34076bf793bacf3cb00ab80eb2890bc5b8a0ccf15e4a19c677973824d5799a57a1d22049b1",
          "sha256": "9ed7f628d1d4a7bc3d07ceb9a9d401c85ddee3e49bae1ceccf08da978f72ea80",
          "sha1": "9172e56aa1d19093c78f038d39b6e27378eb6cce",
          "md5": "de04b806066ecd2bcc95b9812778209e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-54a7145303f0dd9d0f93424a2e124eb4abef5091"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.38.aar",
          "url": "shared_preferences_android_release-0.0.38.aar",
          "size": 12837,
          "sha512": "eccbf136f59649f873f621d8fbb31090958341469213b74ac0303c34076bf793bacf3cb00ab80eb2890bc5b8a0ccf15e4a19c677973824d5799a57a1d22049b1",
          "sha256": "9ed7f628d1d4a7bc3d07ceb9a9d401c85ddee3e49bae1ceccf08da978f72ea80",
          "sha1": "9172e56aa1d19093c78f038d39b6e27378eb6cce",
          "md5": "de04b806066ecd2bcc95b9812778209e"
        }
      ]
    }
  ]
}
