{
  "formatVersion": "1.1",
  "component": {
    "group": "com.instabug.flutter",
    "module": "instabug_flutter_release",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        }
      ],
      "files": [
        {
          "name": "instabug_flutter_release-0.0.31.aar",
          "url": "instabug_flutter_release-0.0.31.aar",
          "size": 118286,
          "sha512": "aafe077aa92eb76ef7a13341d850c80a2a2ae4a5b6567d16234855b8cd2f7096818458be091ceda9000ae7f83c2aad8c9b7d75eaf338cd49eb562706c344661f",
          "sha256": "012af348bae0fac15c96bbb7fe956295466a10515668eab696ca36a91ab8df52",
          "sha1": "e74a88a68308de5921d8c4d21082c523bc0cb27d",
          "md5": "cd48139155f5c035ed0fb42dc4685fdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "com.instabug.library",
          "module": "instabug",
          "version": {
            "requires": "11.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "instabug_flutter_release-0.0.31.aar",
          "url": "instabug_flutter_release-0.0.31.aar",
          "size": 118286,
          "sha512": "aafe077aa92eb76ef7a13341d850c80a2a2ae4a5b6567d16234855b8cd2f7096818458be091ceda9000ae7f83c2aad8c9b7d75eaf338cd49eb562706c344661f",
          "sha256": "012af348bae0fac15c96bbb7fe956295466a10515668eab696ca36a91ab8df52",
          "sha1": "e74a88a68308de5921d8c4d21082c523bc0cb27d",
          "md5": "cd48139155f5c035ed0fb42dc4685fdb"
        }
      ]
    }
  ]
}
