{
  "formatVersion": "1.1",
  "component": {
    "group": "com.liti.mobile",
    "module": "flutter_release",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.29.aar",
          "url": "flutter_release-0.0.29.aar",
          "size": 6220670,
          "sha512": "3055047261880160b2edfec910daabb20357dcbc1c325f75fcb0188accd01b4a23d836fa730abbbc6f6708bc1eecedff69249c9a181dd752a189e07e98a6fa17",
          "sha256": "e7600723ec2b4fdc6f09f0b33388c84ab9f6d6b6306c6afc0d9d2c972ead5fc9",
          "sha1": "71fe4d8adba898b8bc5372d3c0daf7143998c6d1",
          "md5": "19dfee13f488118b7eaa57cabab67501"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.29.aar",
          "url": "flutter_release-0.0.29.aar",
          "size": 6220670,
          "sha512": "3055047261880160b2edfec910daabb20357dcbc1c325f75fcb0188accd01b4a23d836fa730abbbc6f6708bc1eecedff69249c9a181dd752a189e07e98a6fa17",
          "sha256": "e7600723ec2b4fdc6f09f0b33388c84ab9f6d6b6306c6afc0d9d2c972ead5fc9",
          "sha1": "71fe4d8adba898b8bc5372d3c0daf7143998c6d1",
          "md5": "19dfee13f488118b7eaa57cabab67501"
        }
      ]
    }
  ]
}
