{
  "formatVersion": "1.1",
  "component": {
    "group": "com.liti.mobile",
    "module": "flutter_release",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.endigo.plugings.pdfview",
          "module": "flutter_pdfview_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.36.aar",
          "url": "flutter_release-0.0.36.aar",
          "size": 11147236,
          "sha512": "7401b3c720708c8b6379e0bdce72cc6076e6d4a85d727645c7930c3d86c25b2c681ab5d4c1668c0ca3bc30784a458a4d6613b5b42a7cdc99d3180e10dc160eb7",
          "sha256": "7e6230e3748b5f73b3d0be7fede8fb76e2c1f9173f826aef19d68dd9897213a7",
          "sha1": "557c8eb1d4a6f237fa03b983502c26ba167ee089",
          "md5": "b99d0a80c2c3427a760a4f245c6b2704"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.endigo.plugings.pdfview",
          "module": "flutter_pdfview_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.36.aar",
          "url": "flutter_release-0.0.36.aar",
          "size": 11147236,
          "sha512": "7401b3c720708c8b6379e0bdce72cc6076e6d4a85d727645c7930c3d86c25b2c681ab5d4c1668c0ca3bc30784a458a4d6613b5b42a7cdc99d3180e10dc160eb7",
          "sha256": "7e6230e3748b5f73b3d0be7fede8fb76e2c1f9173f826aef19d68dd9897213a7",
          "sha1": "557c8eb1d4a6f237fa03b983502c26ba167ee089",
          "md5": "b99d0a80c2c3427a760a4f245c6b2704"
        }
      ]
    }
  ]
}
