{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_module",
    "module": "flutter_release",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.23"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.23.aar",
          "url": "flutter_release-0.0.23.aar",
          "size": 4817582,
          "sha512": "cce3851794fe70ef5c7fde3f97793068b3d91249a868820d98a386e8eb1db26dda2a09aac6621349397b02dec7bb5c67f090f084d924c4ad1fcce0dc720d7773",
          "sha256": "d02f98a909062a4953213a7c29022ea7c6adce77e297f1eed1549d9dd7e87f10",
          "sha1": "e34154626a7e4fe3de6b348688d4ae1f93a3521d",
          "md5": "befb7f6f7bb3a45e3653774a8c2ff6fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.23"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.23.aar",
          "url": "flutter_release-0.0.23.aar",
          "size": 4817582,
          "sha512": "cce3851794fe70ef5c7fde3f97793068b3d91249a868820d98a386e8eb1db26dda2a09aac6621349397b02dec7bb5c67f090f084d924c4ad1fcce0dc720d7773",
          "sha256": "d02f98a909062a4953213a7c29022ea7c6adce77e297f1eed1549d9dd7e87f10",
          "sha1": "e34154626a7e4fe3de6b348688d4ae1f93a3521d",
          "md5": "befb7f6f7bb3a45e3653774a8c2ff6fd"
        }
      ]
    }
  ]
}
