{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-0.0.33.aar",
          "url": "url_launcher_android_release-0.0.33.aar",
          "size": 21458,
          "sha512": "94bbbcdbd9fa10f2552a147b5936c9fc0f40a590313a34771e88e98504a3acde1a1cd8094fdeea107e33a8067626d67316cf82bf651b6e253a17b01fc1d54aed",
          "sha256": "38842e4a200d8a60edcc337ad2653d3d99bfbe600956592d9e8f9b5327d02f71",
          "sha1": "73dc4f144360608e5bffa2f9058a46ea129517fb",
          "md5": "bd665f776682465c224b396d827cecce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-0.0.33.aar",
          "url": "url_launcher_android_release-0.0.33.aar",
          "size": 21458,
          "sha512": "94bbbcdbd9fa10f2552a147b5936c9fc0f40a590313a34771e88e98504a3acde1a1cd8094fdeea107e33a8067626d67316cf82bf651b6e253a17b01fc1d54aed",
          "sha256": "38842e4a200d8a60edcc337ad2653d3d99bfbe600956592d9e8f9b5327d02f71",
          "sha1": "73dc4f144360608e5bffa2f9058a46ea129517fb",
          "md5": "bd665f776682465c224b396d827cecce"
        }
      ]
    }
  ]
}
