{
  "formatVersion": "1.1",
  "component": {
    "group": "com.liti.mobile",
    "module": "flutter_release",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.endigo.plugings.pdfview",
          "module": "flutter_pdfview_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.34"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.34.aar",
          "url": "flutter_release-0.0.34.aar",
          "size": 11090913,
          "sha512": "edaa965df3728d2128adee63e9ad1096ac8dec55b5550384270809a9e6136595278fad3bd51de4e00b7fb819121b82c89cbaa1d1edf7aee357d4fbfa70b1737b",
          "sha256": "feb93e8d4c5b14e36e5556829f46bbd5dde5fe01c58aaaed5fda0604ef096cae",
          "sha1": "5714a224a6b02c19510425b9c923dbab3e70507f",
          "md5": "7812eb4fd02d41cbc5b563f7b1d07845"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.endigo.plugings.pdfview",
          "module": "flutter_pdfview_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.34"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.34.aar",
          "url": "flutter_release-0.0.34.aar",
          "size": 11090913,
          "sha512": "edaa965df3728d2128adee63e9ad1096ac8dec55b5550384270809a9e6136595278fad3bd51de4e00b7fb819121b82c89cbaa1d1edf7aee357d4fbfa70b1737b",
          "sha256": "feb93e8d4c5b14e36e5556829f46bbd5dde5fe01c58aaaed5fda0604ef096cae",
          "sha1": "5714a224a6b02c19510425b9c923dbab3e70507f",
          "md5": "7812eb4fd02d41cbc5b563f7b1d07845"
        }
      ]
    }
  ]
}
