{
  "formatVersion": "1.1",
  "component": {
    "group": "com.liti.mobile",
    "module": "flutter_release",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.endigo.plugings.pdfview",
          "module": "flutter_pdfview_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.34"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.34.aar",
          "url": "flutter_release-0.0.34.aar",
          "size": 11090911,
          "sha512": "6b0c8cda5fae1b48c3738d34599cd22e503174f52a3f93c39b9514952370fd4f89bbe5db9258e73487d496b63377c29e0af429fa562c10d93cc881e50e827c39",
          "sha256": "07df7784d85e730aec8abcf9e91ddbe7ff8ed8c2a2a5910d8bd8e39da16dbded",
          "sha1": "a9cc4b0473c84567760aa7c36697155e229e22d2",
          "md5": "f6ca8d6bf01825d9fd9c794e4ba82275"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.endigo.plugings.pdfview",
          "module": "flutter_pdfview_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.instabug.flutter",
          "module": "instabug_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.34"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.34.aar",
          "url": "flutter_release-0.0.34.aar",
          "size": 11090911,
          "sha512": "6b0c8cda5fae1b48c3738d34599cd22e503174f52a3f93c39b9514952370fd4f89bbe5db9258e73487d496b63377c29e0af429fa562c10d93cc881e50e827c39",
          "sha256": "07df7784d85e730aec8abcf9e91ddbe7ff8ed8c2a2a5910d8bd8e39da16dbded",
          "sha1": "a9cc4b0473c84567760aa7c36697155e229e22d2",
          "md5": "f6ca8d6bf01825d9fd9c794e4ba82275"
        }
      ]
    }
  ]
}
